detectors:
  UtilityFunction:
    exclude:
      - 'chrome_options'
  IrresponsibleModule:
    exclude:
      - 'HomePage'
      - 'LoginPage'
      - 'RegisterPage'
      - 'Menu'
  FeatureEnvy:
    exclude:
      - 'create_user_api'
  TooManyStatements:
    max_statements: 20
  TooManyInstanceVariables:
    max_instance_variables: 5
